export type Category = "All manufacturing" | "CNC machining" | "Metal fabrication" | "Electronics" | "Textiles & apparel" | "Plastics & molding" | "Packaging";
export type Supplier = {
  id: string; name: string; location: string; region: string; category: Category;
  title: string; description: string; materials: string[]; capabilities: string[];
  minOrder: number; leadDays: number; lead: string; scale: string; image: string; initials: string;
};
// Fictional design fixtures. None of these profiles represents a verified supplier.
export const suppliers: Supplier[] = [
  { id: "precision", name: "Great Lakes Precision", location: "Grand Rapids, MI", region: "Midwest", category: "CNC machining", title: "Precision parts. From one to thousands.", description: "A sample machining partner for custom aluminum housings, brackets, and production components. Explore milling, turning, and finishing in one supplier profile.", materials: ["Aluminum", "Steel", "Brass"], capabilities: ["3- & 5-axis milling", "CNC turning", "Anodizing coordination", "Dimensional inspection"], minOrder: 1, leadDays: 14, lead: "2–4 weeks", scale: "Prototype to production", image: "metal", initials: "GL" },
  { id: "circuits", name: "Pacific Circuit Works", location: "San Jose, CA", region: "West", category: "Electronics", title: "Electronics, ready for your next build.", description: "An example electronics manufacturer for circuit board assembly, component sourcing, and box-build projects. Production requirements are confirmed during quoting.", materials: ["FR-4", "Copper", "Aluminum"], capabilities: ["PCB assembly", "Surface-mount assembly", "Box build", "Functional testing"], minOrder: 25, leadDays: 21, lead: "3–5 weeks", scale: "Small batch to production", image: "circuits", initials: "PC" },
  { id: "textiles", name: "Carolina Sewn", location: "Greensboro, NC", region: "South", category: "Textiles & apparel", title: "Your label. American craftsmanship.", description: "An example cut-and-sew partner for apparel, soft goods, and home textiles. Discuss patterns, samples, fabric sourcing, and private-label production.", materials: ["Cotton", "Linen", "Canvas"], capabilities: ["Cut & sew", "Pattern development", "Private labeling", "Sample development"], minOrder: 100, leadDays: 28, lead: "4–6 weeks", scale: "Small batch to production", image: "textiles", initials: "CS" },
  { id: "metalworks", name: "Keystone Metalworks", location: "Pittsburgh, PA", region: "Northeast", category: "Metal fabrication", title: "Custom metalwork, built to your spec.", description: "An illustrative fabrication shop for sheet metal enclosures, welded assemblies, and custom brackets. Share drawings to define dimensions, tolerances, and finishes.", materials: ["Steel", "Stainless steel", "Aluminum"], capabilities: ["Laser cutting", "Sheet metal bending", "Welding", "Powder coating coordination"], minOrder: 5, leadDays: 14, lead: "2–4 weeks", scale: "Prototype to production", image: "metal", initials: "KM" },
  { id: "polymers", name: "Summit Polymer Studio", location: "Denver, CO", region: "West", category: "Plastics & molding", title: "Take a plastic part from idea to run.", description: "An example partner for prototyping and molding custom plastic parts. Tooling, design review, and production quantities are scoped together.", materials: ["ABS", "Nylon", "Polypropylene"], capabilities: ["Injection molding", "3D printing", "Tooling review", "Part assembly"], minOrder: 250, leadDays: 35, lead: "5–8 weeks", scale: "Production runs", image: "", initials: "SP" },
  { id: "packaging", name: "Heartland Packaging Co.", location: "Columbus, OH", region: "Midwest", category: "Packaging", title: "Packaging that makes it yours.", description: "An illustrative packaging supplier for custom boxes, inserts, and branded shipping materials. Review a sample before committing to a production run.", materials: ["Paperboard", "Corrugated board", "Kraft paper"], capabilities: ["Custom boxes", "Printed cartons", "Protective inserts", "Sample development"], minOrder: 100, leadDays: 21, lead: "3–5 weeks", scale: "Small batch to production", image: "", initials: "HP" },
];
export const categories: Category[] = ["All manufacturing", "CNC machining", "Metal fabrication", "Electronics", "Textiles & apparel", "Plastics & molding", "Packaging"];
export function filterSuppliers({ query = "", category = "All manufacturing", region = "All regions", smallBatch = false, fastLead = false }: { query?: string; category?: string; region?: string; smallBatch?: boolean; fastLead?: boolean }) {
  const normalize = (text: string) => text.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
  const aliases: Record<string, string> = { michigan: "mi", california: "ca", pennsylvania: "pa", colorado: "co", ohio: "oh", manufacturer: "", manufacturers: "", supplier: "", suppliers: "", factories: "", factory: "", parts: "part", products: "product", enclosures: "enclosure", boards: "board", boxes: "box" };
  const canonical = (text: string) => normalize(text).replace(/north carolina/g, "nc").split(/\s+/).map(t => aliases[t] ?? t).filter(Boolean);
  const terms = canonical(query);
  return suppliers.filter(s => (category === "All manufacturing" || s.category === category) && (region === "All regions" || s.region === region) && (!smallBatch || s.minOrder <= 100) && (!fastLead || s.leadDays <= 14) && terms.every(t => canonical([s.name, s.location, s.region, s.category, s.title, s.description, s.scale, ...s.materials, ...s.capabilities].join(" ")).some(word => word === t || (t.length >= 4 && word.startsWith(t)))));
}
