/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BlockReason = "inspection" | "off_platform" | "other" | "service";

export type BookingStatus = "active" | "cancelled" | "completed" | "confirmed" | "disputed" | "inspecting" | "out_for_delivery" | "overdue" | "ready_for_pickup" | "requested" | "return_due";

export type ClaimStatus = "accepted" | "dismissed" | "disputed" | "open" | "settled";

export type ClaimType = "cleaning" | "damage" | "late" | "missing";

export type ConditionKind = "handoff" | "return";

export type DisputeDecision = "dismiss" | "goodwill_credit" | "uphold_full" | "uphold_partial";

export type DisputeStatus = "appealed" | "awaiting_decision" | "more_evidence" | "resolved";

export type ExtensionStatus = "approved" | "cancelled" | "declined" | "requested";

export type ExtraPer = "day" | "rental";

export type Fulfillment = "delivery" | "pickup";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type HoldStatus = "captured" | "expired" | "none" | "partially_captured" | "placed" | "released";

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type LedgerStatus = "available" | "held_claim" | "inspecting" | "paid" | "pending";

export type LedgerType = "claim" | "commission" | "delivery_extras" | "payout" | "refund" | "rental";

export type ListingReviewDecision = "approve" | "reject" | "request_changes";

export type ListingReviewKind = "edited" | "new" | "reported";

export type ListingStatus = "changes_requested" | "draft" | "hidden" | "pending_review" | "published" | "rejected";

export type MessageKind = "photo" | "system" | "text";

export type NotificationChannel = "email";

export type NotificationStatus = "failed" | "queued" | "sending" | "sent" | "skipped";

export type Numeric = ColumnType<number, number | string, number | string>;

export type PaymentKind = "apple_pay" | "card";

export type PayoutStatus = "failed" | "paid" | "paused" | "scheduled";

export type ProfileRole = "provider" | "renter" | "staff";

export type ProfileStatus = "active" | "in_dispute" | "suspended";

export type ProviderKind = "business" | "individual";

export type ReviewMode = "auto_publish_verified" | "manual";

export type ReviewTarget = "listing" | "provider" | "renter";

export type SettingsStatus = "archived" | "draft" | "live";

export type StaffRole = "marketplace_ops" | "trust_safety";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UnitStatus = "in_maintenance" | "rentable" | "retired" | "service_due";

export interface AdminActions {
  action: string;
  actor_id: string | null;
  actor_name: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  occurred_at: Generated<Timestamp>;
  target_id: string | null;
  target_label: string | null;
  target_type: string | null;
  updated_at: Generated<Timestamp>;
}

export interface AvailabilityBlocks {
  created_at: Generated<Timestamp>;
  end_at: Timestamp;
  id: Generated<string>;
  listing_id: string;
  note: string | null;
  reason: Generated<BlockReason>;
  start_at: Timestamp;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface BookingDrafts {
  anonymous_key: string | null;
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: Generated<string>;
  listing_id: string;
  payload: Generated<Json>;
  profile_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface BookingEvents {
  actor_id: string | null;
  actor_name: string | null;
  actor_role: string;
  booking_id: string;
  created_at: Generated<Timestamp>;
  from_status: BookingStatus | null;
  id: Generated<string>;
  occurred_at: Generated<Timestamp>;
  payload: Generated<Json>;
  to_status: BookingStatus | null;
  type: string;
  updated_at: Generated<Timestamp>;
}

export interface BookingExtras {
  amount_cents: number;
  booking_id: string;
  created_at: Generated<Timestamp>;
  days: Generated<number>;
  extra_id: string | null;
  id: Generated<string>;
  is_damage_waiver: Generated<boolean>;
  name: string;
  per: ExtraPer;
  qty: Generated<number>;
  unit_cents: number;
  updated_at: Generated<Timestamp>;
}

export interface Bookings {
  billed_days: number;
  cancellation_policy_snapshot: Json;
  cancellation_snapshot: Json | null;
  cancelled_at: Timestamp | null;
  cancelled_by: string | null;
  charged_cents: number;
  collect_window: Json | null;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  delivery_address: string | null;
  delivery_area: string | null;
  delivery_km: Numeric | null;
  delivery_lat: number | null;
  delivery_lng: number | null;
  drop_window: Json | null;
  end_at: Timestamp;
  free_cancel_until: Timestamp | null;
  fulfillment: Generated<Fulfillment>;
  hold_captured_cents: Generated<number>;
  hold_cents: number;
  hold_expires_at: Timestamp | null;
  hold_placed_at: Timestamp | null;
  hold_released_at: Timestamp | null;
  hold_status: Generated<HoldStatus>;
  id: Generated<string>;
  instant: Generated<boolean>;
  listing_id: string;
  payment_method_id: string | null;
  payment_method_label: string | null;
  payment_refs: Generated<Json>;
  prep_note: string | null;
  price_snapshot: Json;
  provider_id: string;
  qty: Generated<number>;
  ref: Generated<string>;
  renter_id: string;
  return_due_at: Timestamp | null;
  returned_at: Timestamp | null;
  settings_version: number;
  start_at: Timestamp;
  status: Generated<BookingStatus>;
  unit_id: string | null;
  unit_ids: Generated<string[]>;
  updated_at: Generated<Timestamp>;
  van: string | null;
}

export interface CancellationPolicies {
  created_at: Generated<Timestamp>;
  free_until_hours: number;
  id: string;
  is_default: Generated<boolean>;
  name: string;
  provider_cancel_credit_cents: number | null;
  provider_cancel_credit_pct: Numeric | null;
  short_label: string | null;
  tiers: Json;
  updated_at: Generated<Timestamp>;
}

export interface Categories {
  created_at: Generated<Timestamp>;
  icon: string | null;
  id: Generated<string>;
  listing_count_display: number | null;
  name: string;
  parent_id: string | null;
  price_alert_pct: Generated<Numeric>;
  renter_requirements: Generated<string[]>;
  required_documents: Generated<Json>;
  review_mode: Generated<ReviewMode>;
  slug: string;
  sort: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Claims {
  amount_cents: number;
  area: string | null;
  booking_id: string;
  condition_record_id: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  evidence: Generated<Json>;
  id: Generated<string>;
  out_of_service_days: number | null;
  renter_respond_by: Timestamp | null;
  repair_estimate_cents: number | null;
  settled_at: Timestamp | null;
  settled_cents: number | null;
  status: Generated<ClaimStatus>;
  type: ClaimType;
  updated_at: Generated<Timestamp>;
}

export interface ConditionRecords {
  booking_id: string;
  checklist: Generated<Json>;
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  fuel_level: string | null;
  geotag: Json | null;
  id: Generated<string>;
  id_checked_at: Timestamp | null;
  id_matched: boolean | null;
  kind: ConditionKind;
  location_label: string | null;
  notes: string | null;
  photos: Generated<Json>;
  provider_member_id: string | null;
  renter_signature_path: string | null;
  serial_matches: boolean | null;
  serial_scanned: string | null;
  started_at: Generated<Timestamp>;
  unit_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Conversations {
  booking_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_message_at: Timestamp | null;
  last_message_preview: string | null;
  listing_id: string | null;
  provider_id: string;
  provider_unread: Generated<number>;
  renter_id: string;
  renter_unread: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Disputes {
  appeal_by: Timestamp | null;
  assignee_staff_id: string | null;
  booking_id: string;
  charged_cents: number | null;
  claim_id: string | null;
  claimant_profile_id: string | null;
  claimant_provider_id: string | null;
  code: Generated<string>;
  created_at: Generated<Timestamp>;
  decision: DisputeDecision | null;
  decision_due_at: Timestamp;
  evidence_areas: Generated<Json>;
  id: Generated<string>;
  internal_notes: Generated<Json>;
  last_event: string | null;
  last_event_at: Timestamp | null;
  opened_at: Generated<Timestamp>;
  paid_to_provider_cents: number | null;
  reasoning: string | null;
  released_cents: number | null;
  resolved_at: Timestamp | null;
  respondent_profile_id: string | null;
  respondent_provider_id: string | null;
  send_reasoning: Generated<boolean>;
  statements: Generated<Json>;
  status: Generated<DisputeStatus>;
  summary: string;
  updated_at: Generated<Timestamp>;
}

export interface ExtensionRequests {
  amount_cents: number;
  booking_id: string;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  extra_days: number;
  id: Generated<string>;
  new_end_at: Timestamp;
  quote: Generated<Json>;
  status: Generated<ExtensionStatus>;
  updated_at: Generated<Timestamp>;
}

export interface InternalNotes {
  author_id: string | null;
  author_name: string;
  body: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  target_id: string;
  target_type: string;
  updated_at: Generated<Timestamp>;
}

export interface LedgerEntries {
  adjustment_cents: Generated<number>;
  adjustment_label: string | null;
  booking_id: string | null;
  commission_cents: Generated<number>;
  created_at: Generated<Timestamp>;
  description: string | null;
  entry_date: Timestamp;
  gross_cents: Generated<number>;
  id: Generated<string>;
  net_cents: Generated<number>;
  payout_id: string | null;
  provider_id: string;
  status: Generated<LedgerStatus>;
  type: LedgerType;
  updated_at: Generated<Timestamp>;
}

export interface ListingDocuments {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  issued_at: Timestamp | null;
  key: string;
  label: string;
  listing_id: string;
  storage_path: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ListingExtras {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_damage_waiver: Generated<boolean>;
  listing_id: string;
  name: string;
  per: Generated<ExtraPer>;
  price_cents: number;
  sort: Generated<number>;
  updated_at: Generated<Timestamp>;
  waiver_covers_cents: number | null;
}

export interface ListingPhotos {
  created_at: Generated<Timestamp>;
  has_serial_plate: Generated<boolean>;
  id: Generated<string>;
  is_cover: Generated<boolean>;
  is_stock: Generated<boolean>;
  label: string | null;
  listing_id: string;
  photo_hash: string | null;
  sort: Generated<number>;
  storage_path: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ListingReviews {
  assignee_staff_id: string | null;
  change_request: Json | null;
  checks: Generated<Json>;
  created_at: Generated<Timestamp>;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision: ListingReviewDecision | null;
  id: Generated<string>;
  kind: Generated<ListingReviewKind>;
  listing_id: string;
  message_to_provider: string | null;
  previous_day_cents: number | null;
  reasons: Generated<string[]>;
  reject_reason: string | null;
  sla_paused: Generated<boolean>;
  sla_paused_at: Timestamp | null;
  submitted_at: Generated<Timestamp>;
  submitted_snapshot: Json | null;
  updated_at: Generated<Timestamp>;
}

export interface Listings {
  age_years: Numeric | null;
  brand: string | null;
  cancellation_policy_id: string;
  category_id: string;
  cleaning_fee_cents: Generated<number>;
  condition: string | null;
  created_at: Generated<Timestamp>;
  day_cents: number;
  delivery_base_cents: Generated<number>;
  delivery_base_km: Generated<Numeric>;
  delivery_enabled: Generated<boolean>;
  delivery_notes: string | null;
  delivery_per_km_cents: Generated<number>;
  delivery_radius_km: Generated<Numeric>;
  delivery_window_hours: Generated<Numeric>;
  description: Generated<string>;
  hold_cents: number;
  hold_with_waiver_cents: number | null;
  id: Generated<string>;
  id_required: Generated<boolean>;
  included_accessories: Generated<string[]>;
  instant_book: Generated<boolean>;
  last_serviced_at: Timestamp | null;
  late_fee_cents_per_hour: Generated<number>;
  late_grace_minutes: Generated<number>;
  listing_code: Generated<string>;
  max_days: Generated<number>;
  min_days: Generated<number>;
  min_renter_age: Generated<number>;
  model: string | null;
  month_cents: number | null;
  pickup_address: string | null;
  pickup_enabled: Generated<boolean>;
  pickup_hours: Generated<Json>;
  pickup_hours_label: string | null;
  pickup_instructions: string | null;
  pickup_lat: number | null;
  pickup_lng: number | null;
  prep_hours: Generated<Numeric>;
  provider_id: string;
  published_at: Timestamp | null;
  quality_score: number | null;
  rating: Numeric | null;
  rating_count: Generated<number>;
  rules: Generated<string[]>;
  same_day_cutoff_minutes: Generated<number>;
  search_text: Generated<string | null>;
  slug: string;
  specs: Generated<Json>;
  status: Generated<ListingStatus>;
  title: string;
  updated_at: Generated<Timestamp>;
  week_cents: number | null;
  weekend_cents: number | null;
}

export interface MarketplaceSettingsVersions {
  change_summary: string | null;
  changes: Generated<Json>;
  config: Json;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  published_at: Timestamp | null;
  published_by: string | null;
  status: Generated<SettingsStatus>;
  updated_at: Generated<Timestamp>;
  version: number;
}

export interface Messages {
  body: string | null;
  conversation_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: Generated<MessageKind>;
  photo_path: string | null;
  read_at: Timestamp | null;
  sender_id: string | null;
  sender_side: string;
  updated_at: Generated<Timestamp>;
}

export interface NotificationDeliveries {
  attempts: Generated<number>;
  body_text: string | null;
  booking_id: string | null;
  channel: Generated<NotificationChannel>;
  created_at: Generated<Timestamp>;
  dedupe_key: string;
  error: string | null;
  id: Generated<string>;
  last_attempt_at: Timestamp | null;
  party: string | null;
  payload: Generated<Json>;
  provider: string;
  provider_ref: string | null;
  reason: string | null;
  recipient_email: string | null;
  recipient_profile_id: string | null;
  sent_at: Timestamp | null;
  status: Generated<NotificationStatus>;
  subject: string | null;
  template: string;
  updated_at: Generated<Timestamp>;
}

export interface OtpCodes {
  code: string;
  consumed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  identifier: string;
  updated_at: Generated<Timestamp>;
}

export interface PaymentMethods {
  brand: string;
  created_at: Generated<Timestamp>;
  exp_month: number | null;
  exp_year: number | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  kind: Generated<PaymentKind>;
  last4: string;
  profile_id: string;
  provider_ref: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Payouts {
  account_masked: string | null;
  amount_cents: number;
  created_at: Generated<Timestamp>;
  exception: string | null;
  exception_detail: string | null;
  id: Generated<string>;
  paid_at: Timestamp | null;
  provider_id: string;
  rental_count: Generated<number>;
  scheduled_for: Timestamp;
  status: Generated<PayoutStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Profiles {
  avatar_path: string | null;
  completed_count: Generated<number>;
  created_at: Generated<Timestamp>;
  email: string | null;
  flags: Generated<string[]>;
  id: string;
  id_verified: Generated<boolean>;
  id_verified_at: Timestamp | null;
  id_verified_method: string | null;
  is_business: Generated<boolean>;
  joined_at: Generated<Timestamp>;
  late_return_count: Generated<number>;
  name: string;
  neighbourhood: string | null;
  notification_prefs: Generated<Json>;
  phone: string | null;
  public_id: Generated<number>;
  rating_count: Generated<number>;
  rating_from_providers: Numeric | null;
  role: Generated<ProfileRole>;
  status: Generated<ProfileStatus>;
  stripe_customer_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface ProviderMembers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  profile_id: string;
  provider_id: string;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Providers {
  about: string | null;
  accepting_bookings: Generated<boolean>;
  address: string | null;
  completed_count: Generated<number>;
  created_at: Generated<Timestamp>;
  delivery_vans: Generated<Json>;
  id: Generated<string>;
  insurance_valid_until: Timestamp | null;
  kind: Generated<ProviderKind>;
  lat: number | null;
  lng: number | null;
  name: string;
  neighbourhood: string | null;
  on_time_pct: Numeric | null;
  opening_hours: Generated<Json>;
  owner_profile_id: string;
  payout_account_masked: string | null;
  payout_account_verified: Generated<boolean>;
  payout_schedule: Generated<string>;
  payouts_paused: Generated<boolean>;
  payouts_paused_reason: string | null;
  rating: Numeric | null;
  rating_count: Generated<number>;
  response_minutes: number | null;
  slug: string;
  tax_id: string | null;
  tax_id_verified: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  verified: Generated<boolean>;
  years_on_platform: number | null;
}

export interface PublicProfiles {
  avatar_path: string | null;
  completed_count: number | null;
  id: string | null;
  is_business: boolean | null;
  joined_at: Timestamp | null;
  name: string | null;
  neighbourhood: string | null;
  rating_count: number | null;
  rating_from_providers: Numeric | null;
}

export interface RenterCredits {
  amount_cents: number;
  booking_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  profile_id: string;
  reason: string;
  updated_at: Generated<Timestamp>;
  used_at: Timestamp | null;
}

export interface Reports {
  body: string | null;
  booking_id: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  listing_id: string | null;
  reporter_id: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface Reviews {
  author_id: string;
  author_side: string;
  body: string | null;
  booking_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  item_stars: number | null;
  listing_id: string | null;
  photos: Generated<Json>;
  provider_id: string | null;
  provider_stars: number | null;
  published_at: Timestamp | null;
  renter_id: string | null;
  renter_stars: number | null;
  submitted_at: Generated<Timestamp>;
  tags: Generated<string[]>;
  target: ReviewTarget;
  updated_at: Generated<Timestamp>;
}

export interface SavedListings {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  listing_id: string;
  profile_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Staff {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  permissions: Generated<string[]>;
  profile_id: string;
  resolved_count: Generated<number>;
  role: StaffRole;
  two_factor: Generated<boolean>;
  updated_at: Generated<Timestamp>;
}

export interface Units {
  acquired_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  hours: number | null;
  id: Generated<string>;
  listing_id: string;
  next_service_at: Timestamp | null;
  serial: string;
  status: Generated<UnitStatus>;
  unit_number: number;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  admin_actions: AdminActions;
  availability_blocks: AvailabilityBlocks;
  booking_drafts: BookingDrafts;
  booking_events: BookingEvents;
  booking_extras: BookingExtras;
  bookings: Bookings;
  cancellation_policies: CancellationPolicies;
  categories: Categories;
  claims: Claims;
  condition_records: ConditionRecords;
  conversations: Conversations;
  disputes: Disputes;
  extension_requests: ExtensionRequests;
  internal_notes: InternalNotes;
  ledger_entries: LedgerEntries;
  listing_documents: ListingDocuments;
  listing_extras: ListingExtras;
  listing_photos: ListingPhotos;
  listing_reviews: ListingReviews;
  listings: Listings;
  marketplace_settings_versions: MarketplaceSettingsVersions;
  messages: Messages;
  notification_deliveries: NotificationDeliveries;
  otp_codes: OtpCodes;
  payment_methods: PaymentMethods;
  payouts: Payouts;
  profiles: Profiles;
  provider_members: ProviderMembers;
  providers: Providers;
  public_profiles: PublicProfiles;
  renter_credits: RenterCredits;
  reports: Reports;
  reviews: Reviews;
  saved_listings: SavedListings;
  staff: Staff;
  units: Units;
}
