"use client";
import { useEffect, useState } from 'react';
import { flushSync } from 'react-dom';
import { Icon, type IconName } from '@/components/ui/icons';
import { DialogRoot, DialogContent } from '@/components/ui/dialog';
import { categories, suppliers, filterSuppliers, type Category, type Supplier } from '@/lib/manufacturing/catalog';
import { capacity, products, sampleProject, type Brief, type Product, type Project } from '@/lib/manufacturing/sourcing';
import { SupplierProfile, ManufacturerOnboarding } from './workspace';
import BriefBuilder from './brief-builder';
import ProjectWorkspace from './project-workspace';
import SupplierDesk from './supplier-desk';
import { ProductCard, ProductDetail } from './wholesale';
import type { CapacityOverride } from './supplier-evidence';
import './marketplace.css';
const categoryIcons:IconName[]=['grid','gear','construction','laptop','tag','box','inventory'];
function blankBrief():Brief {return {id:crypto.randomUUID(),title:'',description:'',quantity:0,process:'Need advice',material:'',dimensions:'',finish:'',destination:'',target:'',requirements:'',files:[],supplierIds:[],kind:'custom'};}
export default function ManufacturingMarketplace() {
 const [view,setView]=useState<'market'|'projects'|'supplier'>('market');
 const [mode,setMode]=useState<'custom'|'wholesale'>('custom');
 const [category,setCategory]=useState<Category>('All manufacturing');
 const [query,setQuery]=useState('');const [search,setSearch]=useState('');
 const [region,setRegion]=useState('All regions');const [smallBatch,setSmallBatch]=useState(false);const [fastLead,setFastLead]=useState(false);const [openOnly,setOpenOnly]=useState(false);
 const [saved,setSaved]=useState<string[]>([]);const [compare,setCompare]=useState<string[]>([]);const [shortlistOnly,setShortlistOnly]=useState(false);
 const [productDraft,setProductDraft]=useState<Brief|undefined>();
 const [selected,setSelected]=useState<Supplier|null>(null);const [product,setProduct]=useState<Product|null>(null);
 const [dialog,setDialog]=useState<'brief'|'compare'|'onboarding'|null>(null);const [notice,setNotice]=useState('');
 const [projects,setProjects]=useState<Project[]>([sampleProject]);const [projectId,setProjectId]=useState(sampleProject.brief.id);
 const [draft,setDraft]=useState<Brief|null>(null);const [availability,setAvailability]=useState<Record<string,CapacityOverride>>({});
 const project=projects.find(p=>p.brief.id===projectId)??projects[0]!;
 useEffect(()=>{try{const v:unknown=JSON.parse(localStorage.getItem('fab-manufacturing-shortlist')||'[]');if(Array.isArray(v))queueMicrotask(()=>setSaved(v.filter((id):id is string=>typeof id==='string'&&suppliers.some(s=>s.id===id))));}catch{/* optional storage */}},[]);
 function toggleSave(id:string){const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);try{localStorage.setItem('fab-manufacturing-shortlist',JSON.stringify(next));}catch{setNotice('Saved for this tab; browser storage is unavailable.');}}
 function resetFilters(){setCategory('All manufacturing');setQuery('');setSearch('');setRegion('All regions');setSmallBatch(false);setFastLead(false);setOpenOnly(false);setShortlistOnly(false);}
 function browse(){setView('market');window.scrollTo({top:0,behavior:'smooth'});}
 function showProjects(){setView('projects');window.scrollTo({top:0,behavior:'smooth'});}
 function startBrief(targets?:Supplier[]){const b=draft??blankBrief();const ids=(targets??suppliers.filter(s=>saved.includes(s.id))).map(s=>s.id);setDraft({...b,supplierIds:[...new Set([...b.supplierIds,...ids])],process:!draft&&targets?.length===1?targets[0]!.category:b.process});setSelected(null);setNotice('');setDialog('brief');}
 function createProject(b:Brief){setProjects(ps=>[...ps,{brief:b,example:false,offers:[],questions:[]}]);setProjectId(b.id);setDialog(null);setProduct(null);setDraft(null);showProjects();setNotice('Project draft created in this tab. No suppliers contacted.');}
 function updateProject(p:Project){setProjects(ps=>ps.map(x=>x.brief.id===p.brief.id?p:x));}
 function editProject(){if(project.brief.catalog){const item=products.find(p=>p.id===project.brief.catalog!.productId);if(item){setProductDraft(project.brief);setProduct(item);setNotice('Editing creates a revised inquiry and recalculates the catalog estimate.');return;}}setDraft({...project.brief,id:crypto.randomUUID()});setDialog('brief');setNotice('Editing creates a revised draft. The original project and its example quotes are retained.');}
 function openProduct(p:Product){setProductDraft(undefined);setProduct(p);}
 function toggleCompare(id:string){if(compare.includes(id))setCompare(compare.filter(x=>x!==id));else if(compare.length<3)setCompare([...compare,id]);else setNotice('Compare up to 3 manufacturers. Remove one to add another.');}
 function isAvailable(id:string){const a=availability[id];return a?a.accepting&&(!a.expires||new Date(a.expires+'T23:59:59')>=new Date()):capacity(id).accepting;}
 useEffect(()=>{type Context={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>unknown};const context=(document as Document&{modelContext?:Context}).modelContext;if(!context?.registerTool)return;const c=new AbortController();try{void Promise.resolve(context.registerTool({name:'search_example_manufacturers',description:'Search the fictional manufacturing catalog and show matching manufacturers. Does not contact suppliers.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){if(!input||typeof input!=='object'||!('query'in input)||typeof input.query!=='string'||input.query.length>200||Object.keys(input).some(k=>k!=='query'))throw new Error('Provide a query string of at most 200 characters.');const q=input.query;flushSync(()=>{setQuery(q);setSearch(q);setCategory('All manufacturing');setRegion('All regions');setSmallBatch(false);setFastLead(false);setOpenOnly(false);setShortlistOnly(false);setView('market');setMode('custom');});return {exampleSuppliers:filterSuppliers({query:q}).map(s=>({id:s.id,name:s.name,category:s.category,location:s.location})),liveConnections:false};}},{signal:c.signal})).catch(()=>{});}catch{/* optional browser capability */}return()=>c.abort();},[]);
 const results=filterSuppliers({query:search,category,region,smallBatch,fastLead}).filter(s=>(!shortlistOnly||saved.includes(s.id))&&(!openOnly||isAvailable(s.id)));
 const productResults=products.filter(p=>(category==='All manufacturing'||category===p.category)&&(region==='All regions'||suppliers.find(s=>s.id===p.supplierId)?.region===region)&&`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(search.toLowerCase().trim()));
 return <div className="fab-app fab-v2">
  <div className="fab-announcement"><span><span className="fab-dot"/>American manufacturing, within reach.</span><span>Interactive demo · Example suppliers & offers</span></div>
  <header className="fab-header"><button className="fab-logo" onClick={()=>{resetFilters();browse();}}>fab<span className="fab-domain">.rent</span><span className="fab-logo-mark">↗</span></button><span className="fab-wordmark-note">THE AMERICAN<br/>MANUFACTURING MARKETPLACE</span><nav aria-label="Main navigation"><button className={view==='market'?'active':''} onClick={browse}>Marketplace</button><button className={view==='projects'?'active':''} onClick={showProjects}>My projects <span>{projects.length}</span></button></nav><button className="fab-header-supplier" onClick={()=>{setView('supplier');window.scrollTo({top:0});}}>For manufacturers</button><button className="fab-button fab-dark" onClick={()=>startBrief()}>{draft?'Continue sourcing brief':'Help me source this'} <Icon name="plus" size={17}/></button></header>
  <nav className="fab-mobile-tools" aria-label="Sourcing tools"><button onClick={browse}><Icon name="grid" size={17}/>Browse</button><button onClick={showProjects}><Icon name="file" size={17}/>Projects ({projects.length})</button><button onClick={()=>setView('supplier')}><Icon name="users" size={17}/>Manufacturers</button></nav>
  <div className="fab-layout"><aside className="fab-sidebar"><p className="fab-label">EXPLORE CAPABILITIES</p><nav aria-label="Manufacturing categories">{categories.map((c,i)=><button key={c} aria-pressed={category===c&&view==='market'} className={category===c&&view==='market'?'active':''} onClick={()=>{setCategory(c);setShortlistOnly(false);setSearch('');setQuery('');browse();}}><Icon name={categoryIcons[i]??'box'} size={18}/><span>{c}</span></button>)}</nav><div className="fab-sidebar-divider"/><p className="fab-label">YOUR SOURCING DESK</p><button className="fab-side-action" onClick={()=>{resetFilters();setShortlistOnly(true);setMode('custom');browse();}}><Icon name="heart"/>Shortlist <span>{saved.length}</span></button><button className="fab-side-action" onClick={showProjects}><Icon name="file"/>Project workspace</button><button className="fab-side-action" onClick={()=>{setProjectId(sampleProject.brief.id);showProjects();}}><Icon name="coins"/>Try quote comparison</button><div className="fab-sidebar-note"><span className="fab-asterisk">✳</span><h3>From idea<br/>to a clear brief.</h3><p>You don’t need to know every manufacturing term to get started.</p><button onClick={()=>startBrief()}>Help me source this <Icon name="chevron-right" size={16}/></button></div></aside>
  <main id="main" className="fab-main">{view==='market'?<>
   <div className="fab-market-heading"><div><span className="fab-eyebrow">AMERICA’S MANUFACTURING MARKETPLACE</span><h1>{mode==='custom'?'Find the factory that can make it.':'Find products ready for your business.'}</h1></div><span className="fab-pilot-label">Explore the sourcing pilot</span></div>
   <section className="fab-search-section" aria-label="Search manufacturing"><div className="fab-search-tabs" role="group" aria-label="Buying path"><button aria-pressed={mode==='custom'} className={mode==='custom'?'active':''} onClick={()=>{setMode('custom');resetFilters();}}>Have it made <span>Custom manufacturing</span></button><button aria-pressed={mode==='wholesale'} className={mode==='wholesale'?'active':''} onClick={()=>{setMode('wholesale');resetFilters();}}>Buy wholesale <span>Products & samples</span></button></div><form className="fab-search" onSubmit={e=>{e.preventDefault();setSearch(query);}}><Icon name="search" size={22}/><input aria-label={mode==='custom'?'What do you need made?':'Search wholesale products'} maxLength={200} placeholder={mode==='custom'?'What do you need made? Try “aluminum parts”':'Search products, materials, or categories'} value={query} onChange={e=>setQuery(e.target.value)}/><label className="fab-location"><Icon name="pin" size={17}/><select aria-label="Manufacturing region" value={region} onChange={e=>setRegion(e.target.value)}>{['All regions','Midwest','West','South','Northeast'].map(r=><option key={r}>{r}</option>)}</select></label><button type="submit" className="fab-button fab-dark">{mode==='custom'?'Find manufacturers':'Find products'}<Icon name="search" size={17}/></button></form><div className="fab-popular"><span>Try a search</span>{(mode==='custom'?['CNC machining','PCB assembly','Cotton','Custom boxes']:['Aluminum','PCB','Cotton']).map(t=><button key={t} onClick={()=>{resetFilters();setQuery(t);setSearch(t);}}>{t}<Icon name="chevron-right" size={13}/></button>)}</div></section>
   <div className="fab-sourcing-banner"><div><Icon name={mode==='custom'?'file':'box'} size={28}/><div><h2>{mode==='custom'?'Start with your idea. We’ll help shape the brief.':'Order sizes, variants, and samples—all in one place.'}</h2><p>{mode==='custom'?'Describe your project, attach a drawing, and explore suitable manufacturing processes.':'Explore example quantity pricing, then prepare a sample request or wholesale inquiry.'}</p></div></div><button className="fab-button fab-outline" onClick={()=>mode==='custom'?startBrief():openProduct(products[0]!)}>{mode==='custom'?'Help me source this':'Explore a product'}<Icon name="chevron-right" size={17}/></button></div>
   <section id="manufacturers" className="fab-results" aria-labelledby="results-heading"><div className="fab-section-heading"><div><span className="fab-eyebrow">{mode==='custom'?'CAPABILITY. CAPACITY. CONFIDENCE.':'WHOLESALE CATALOG'}</span><h2 id="results-heading">{shortlistOnly?'Your supplier shortlist':search?`Results for “${search}”`:category!=='All manufacturing'?category:mode==='custom'?'Meet your next manufacturing partner.':'Products to build your business.'}</h2></div><span>{mode==='custom'?`${results.length} example suppliers`:`${productResults.length} example products`}</span></div>
   {mode==='custom'?<><div className="fab-filterbar"><div className="fab-filter-chips"><button aria-pressed={openOnly} className={openOnly?'selected':''} onClick={()=>setOpenOnly(!openOnly)}>Considering new work</button><button aria-pressed={smallBatch} className={smallBatch?'selected':''} onClick={()=>setSmallBatch(!smallBatch)}>Minimum order ≤ 100</button><button aria-pressed={fastLead} className={fastLead?'selected':''} onClick={()=>setFastLead(!fastLead)}>Lead starts within 2 weeks</button><button onClick={resetFilters}>Clear filters</button></div><button className="fab-shortlist-toggle" onClick={()=>{resetFilters();setShortlistOnly(!shortlistOnly);}}><Icon name="heart" size={16}/>{shortlistOnly?'All suppliers':`Shortlist (${saved.length})`}</button></div><div className="fab-grid">{results.map(s=><article key={s.id} className="fab-supplier-card"><div className={`fab-card-media fab-media-${s.image||'plain'}`}><span className="fab-category-tag">{s.category}</span><button className="fab-save" onClick={()=>toggleSave(s.id)} aria-label={`${saved.includes(s.id)?'Unsave':'Save'} ${s.name}`} aria-pressed={saved.includes(s.id)}><Icon name={saved.includes(s.id)?'heart-filled':'heart'} size={18}/></button>{s.image?<img src={`/manufacturing/${s.image}.png`} alt={`Illustrative ${s.category.toLowerCase()}`} loading="lazy"/>:<div className="fab-media-type"><Icon name={categoryIcons[categories.indexOf(s.category)]??'box'} size={42}/><span>{s.category}</span></div>}<span className="fab-example-tag">EXAMPLE MANUFACTURER</span></div><div className="fab-card-body"><div className="fab-company"><span className="fab-company-logo">{s.initials}</span><div><h3>{s.name}</h3><span><Icon name="pin" size={13}/>{s.location}</span></div></div><h4>{s.title}</h4><div className="fab-materials">{s.materials.map(m=><span key={m}>{m}</span>)}</div><dl className="fab-card-specs"><div><dt>Min. order</dt><dd>{s.minOrder} units</dd></div><div><dt>Typical lead</dt><dd>{s.lead}</dd></div></dl><div className={`fab-capacity-line ${isAvailable(s.id)?'is-open':''}`}><Icon name="calendar" size={16}/><span>{isAvailable(s.id)?availability[s.id]?.available||capacity(s.id).available:'Availability needs confirmation'}</span></div><button className="fab-evidence-link" onClick={()=>setSelected(s)}><Icon name="shield" size={15}/>Evidence not verified <Icon name="chevron-right" size={15}/></button><div className="fab-card-footer"><button onClick={()=>setSelected(s)}>View factory <Icon name="chevron-right" size={17}/></button><button className="fab-compare-button" onClick={()=>toggleCompare(s.id)} aria-pressed={compare.includes(s.id)}><Icon name={compare.includes(s.id)?'check':'plus'} size={16}/>{compare.includes(s.id)?'Selected':'Compare'}</button></div></div></article>)}</div></>:<div className="fab-grid fab-wholesale-grid">{productResults.map(p=><ProductCard key={p.id} product={p} onOpen={()=>openProduct(p)}/>)}</div>}
   {(mode==='custom'?results.length:productResults.length)===0&&<div className="fab-empty"><Icon name="search" size={30}/><h3>{shortlistOnly?'Save your first manufacturer':'No matches in the example catalog'}</h3><p>Try a broader search, or create a sourcing brief.</p><div className="fab-form-actions"><button className="fab-button fab-outline" onClick={resetFilters}>Clear filters</button><button className="fab-button fab-dark" onClick={()=>startBrief()}>Help me source this</button></div></div>}</section>
   <section className="fab-workspace-banner"><div><span className="fab-eyebrow">FROM SOURCING TO A BETTER DECISION</span><h2>The lowest unit price isn’t always the lowest cost.</h2><p>Explore a sample project with three offers, supplier questions, and a complete cost comparison.</p></div><button className="fab-button fab-dark" onClick={()=>{setProjectId(sampleProject.brief.id);showProjects();}}>Open example project <Icon name="chevron-right" size={17}/></button></section>
   <footer className="fab-footer"><span className="fab-footer-logo">fab.rent</span><p>Made possible, closer to home.</p><span>Example data · No live orders or messages</span></footer>
  </>:<><div className="fab-project-picker"><button onClick={browse}><Icon name="back" size={17}/>Marketplace</button><label>Project<select aria-label="Active project" value={projectId} onChange={e=>setProjectId(e.target.value)}>{projects.map(p=><option key={p.brief.id} value={p.brief.id}>{p.example?'Example: ':'Draft: '}{p.brief.title}</option>)}</select></label></div>{view==='projects'?<ProjectWorkspace key={project.brief.id} project={project} onChange={updateProject} onEdit={editProject} onNew={()=>startBrief()} onSample={()=>setProjectId(sampleProject.brief.id)} onSupplier={()=>setView('supplier')}/>:<SupplierDesk key={project.brief.id} project={project} onChange={updateProject} onCapacity={(id,c)=>setAvailability(a=>({...a,[id]:c}))} onBuyer={showProjects} onProfile={()=>setDialog('onboarding')}/>}</>}
  </main></div>
  {view==='market'&&mode==='custom'&&compare.length>0&&<div className="fab-compare-tray"><span><strong>{compare.length}/3</strong> factories selected</span><button className="fab-button fab-dark" disabled={compare.length<2} onClick={()=>setDialog('compare')}>Compare capabilities</button><button aria-label="Clear comparison" onClick={()=>setCompare([])}><Icon name="close" size={18}/></button></div>}
  {notice&&<div className="fab-toast" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><Icon name="close" size={18}/></button></div>}
  <DialogRoot open={dialog==='brief'} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent title="What would you like to make?" description="Build a clear brief—even if you are still figuring out the details." size="lg" className="fab-dialog">{draft&&<BriefBuilder key={draft.id} initial={draft} onChange={setDraft} onCreate={createProject}/>}</DialogContent></DialogRoot>
  <DialogRoot open={!!selected} onOpenChange={open=>{if(!open)setSelected(null);}}><DialogContent title={selected?.name??'Manufacturer'} description="Capabilities, production availability, and the evidence behind them." size="lg" className="fab-dialog">{selected&&<SupplierProfile supplier={selected} onQuote={()=>startBrief([selected])} onSave={()=>toggleSave(selected.id)} saved={saved.includes(selected.id)} availability={availability[selected.id]}/>}</DialogContent></DialogRoot>
  <DialogRoot open={!!product} onOpenChange={open=>{if(!open)setProduct(null);}}><DialogContent title="Product details & quantity pricing" description="Illustrative wholesale catalog. No purchase or payment is made." size="lg" className="fab-dialog">{product&&<ProductDetail key={`${product.id}-${productDraft?.id??'new'}`} product={product} initial={productDraft} onDraft={createProject}/>}</DialogContent></DialogRoot>
  <DialogRoot open={dialog==='onboarding'} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent title="Put your factory on the map." description="Prepare a profile for your actual production location and capabilities." size="lg" className="fab-dialog"><ManufacturerOnboarding/></DialogContent></DialogRoot>
  <DialogRoot open={dialog==='compare'} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent title="Compare manufacturing capabilities" description="Example specifications. Project quotes are compared in your workspace." size="lg" className="fab-dialog"><div className="fab-workspace"><div className="fab-compare-scroll"><table className="fab-comparison"><thead><tr><th scope="col">Project fit</th>{suppliers.filter(s=>compare.includes(s.id)).map(s=><th scope="col" key={s.id}>{s.name}</th>)}</tr></thead><tbody>{([['Location',(s:Supplier)=>s.location],['Process',(s:Supplier)=>s.category],['Materials',(s:Supplier)=>s.materials.join(', ')],['Minimum order',(s:Supplier)=>`${s.minOrder} units`],['Typical lead',(s:Supplier)=>s.lead],['Production scale',(s:Supplier)=>s.scale],['Evidence',()=> 'Example only · Not verified']] as [string,(s:Supplier)=>string][]).map(([label,fn])=><tr key={label}><th scope="row">{label}</th>{suppliers.filter(s=>compare.includes(s.id)).map(s=><td key={s.id}>{fn(s)}</td>)}</tr>)}</tbody></table></div><div className="fab-form-actions"><button className="fab-button fab-outline" onClick={()=>setDialog(null)}>Keep browsing</button><button className="fab-button fab-dark" onClick={()=>startBrief(suppliers.filter(s=>compare.includes(s.id)))}>Create a shared sourcing brief</button></div></div></DialogContent></DialogRoot>
 </div>;
}
