"use client";
import { useState } from 'react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Icon } from '@/components/ui/icons';
import { suppliers } from '@/lib/manufacturing/catalog';
import { briefText, comparable, downloadDraft, money, subtotal, type Offer, type Project } from '@/lib/manufacturing/sourcing';
import { LocalAttachment } from './brief-builder';
export default function ProjectWorkspace({ project:p, onChange, onEdit, onNew, onSample, onSupplier }: { project:Project; onChange:(p:Project)=>void; onEdit:()=>void; onNew:()=>void; onSample:()=>void; onSupplier:()=>void }) {
  const [tab,setTab]=useState('brief');
  const [message,setMessage]=useState('');
  const [notice,setNotice]=useState('');
  const eligible=p.offers.filter(o=>comparable(o,p.brief.quantity));
  const lowest=eligible.length?Math.min(...eligible.map(subtotal)):null;
  const fastest=eligible.length?Math.min(...eligible.map(o=>o.leadDays)):null;
  const selected=p.offers.find(o=>o.id===p.selectedOffer);
  const rows:[string,(o:Offer)=>string][]=[['Quantity',o=>o.quantity.toLocaleString()],['Unit price',o=>money(o.unitCents)],['Parts subtotal',o=>money(o.quantity*o.unitCents)],['Tooling / setup',o=>money(o.toolingCents)],['Shipping',o=>money(o.shippingCents)],['Inspection',o=>money(o.inspectionCents)],['Quoted subtotal',o=>money(subtotal(o))],['Lead time',o=>`${o.leadDays} days after approval`],['Validity',o=>o.validUntil],['Specification',o=>o.specification],['Exclusions',o=>o.exclusions]];
  function select(o:Offer){onChange({...p,selectedOffer:o.id});setNotice(`${o.supplier} selected in this demo. No order or payment has been placed.`);}
  return <section className="fab-project-screen">
    <div className="fab-project-heading"><div><span className="fab-eyebrow">{p.example?'EXAMPLE SOURCING PROJECT':'PROJECT DRAFT · THIS TAB ONLY'}</span><h1>{p.brief.title}</h1><p>{p.brief.quantity.toLocaleString()} {p.brief.kind==='wholesale'?'catalog units':'parts'} · {p.brief.destination} · {p.brief.target||'Delivery date flexible'}</p></div><button className="fab-button fab-outline" onClick={onNew}><Icon name="plus" size={17}/>New project</button></div>
    <div className="fab-notice"><Icon name="info" size={18}/><span>{p.example?'All offers and conversations below are illustrative. Explore the comparison and supplier reply flows.':'This draft and its files stay in this browser tab. No suppliers have received it, and no real quotes have been requested.'}</span>{!p.example&&<button onClick={onSample}>Explore example offers</button>}</div>
    <Tabs value={tab} onValueChange={setTab} className="fab-project-tabs">
      <TabsList><TabsTrigger value="brief">Project brief</TabsTrigger><TabsTrigger value="offers" count={p.offers.length}>Compare quotes</TabsTrigger><TabsTrigger value="questions" count={p.questions.length}>Questions</TabsTrigger><TabsTrigger value="next">Next steps</TabsTrigger></TabsList>
      <TabsContent value="brief" className="fab-tab-panel"><div className="fab-project-columns"><div className="fab-surface"><div className="fab-panel-heading"><h2>One brief for every supplier</h2><button onClick={onEdit}>Edit brief <Icon name="edit" size={15}/></button></div><p className="fab-project-description">{p.brief.description}</p><dl className="fab-detail-grid">{[['Process',p.brief.process],['Material',p.brief.material||'Needs advice'],['Dimensions & tolerances',p.brief.dimensions||'To be confirmed'],['Finish',p.brief.finish||'To be confirmed'],['Target delivery',p.brief.target||'Flexible'],['Destination',p.brief.destination]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><h3>Quality & other requirements</h3><p>{p.brief.requirements||'No additional requirements supplied.'}</p><div className="fab-panel-heading"><h3>Drawings & files</h3><span>{p.brief.files.length} attached</span></div>{p.brief.files.length?p.brief.files.map((file,i)=><LocalAttachment key={`${file.name}-${i}`} file={file}/>):<p className="fab-muted">No drawings attached. Add them when available; dimensions and specifications still need supplier review.</p>}<button className="fab-button fab-outline" onClick={()=>{downloadDraft('fab-sourcing-brief.txt',briefText(p.brief));setNotice('Brief download prepared. Attachments are listed, not included.');}}><Icon name="download" size={17}/>Download brief</button></div>
      <aside className="fab-surface fab-project-sidebar"><span className="fab-eyebrow">YOUR SUPPLIER SHORTLIST</span><h2>Partners for this project</h2>{p.brief.supplierIds.length?p.brief.supplierIds.map(id=>{const s=suppliers.find(x=>x.id===id);return s&&<div className="fab-project-supplier" key={id}><strong>{s.name}</strong><span>{s.location}</span><small>{p.example?'Included in example project':'Not contacted'}</small></div>;}):<p className="fab-muted">Add example manufacturers while editing the brief.</p>}<button className="fab-button fab-dark" onClick={()=>setTab('offers')}>Compare quotes <Icon name="chevron-right" size={17}/></button><button className="fab-button fab-outline" onClick={onSupplier}>Try a supplier response</button><p className="fab-muted">Supplier replies are simulated within this preview.</p></aside></div></TabsContent>
      <TabsContent value="offers" className="fab-tab-panel"><div className="fab-panel-heading"><div><h2>Compare the complete quoted cost.</h2><p>All amounts in USD. Taxes excluded. This is not a landed-cost estimate.</p></div><button className="fab-button fab-outline" onClick={onSupplier}>Add demo quote</button></div>{p.offers.length?<><div className="fab-offer-highlights"><div><small>Lowest comparable subtotal</small><strong>{lowest===null?'No comparable offers':money(lowest)}</strong></div><div><small>Fastest comparable production</small><strong>{fastest===null?'To be confirmed':`${fastest} days`}</strong></div><div><small>Selected for discussion</small><strong>{selected?.supplier||'Choose after reviewing the details'}</strong></div></div>
      <div className="fab-offer-desktop fab-table-scroll"><table className="fab-offer-table"><thead><tr><th scope="col">Your requirement<br/><small>{p.brief.quantity.toLocaleString()} units · same brief</small></th>{p.offers.map(o=><th scope="col" key={o.id}><strong>{o.supplier}</strong><span>{!comparable(o,p.brief.quantity)?'Review differences':subtotal(o)===lowest?'Lowest subtotal':o.leadDays===fastest?'Fastest production':'Comparable offer'}</span></th>)}</tr></thead><tbody>{rows.map(([label,fn])=><tr className={label==='Quoted subtotal'?'fab-total-row':''} key={label}><th scope="row">{label}</th>{p.offers.map(o=><td key={o.id}>{fn(o)}</td>)}</tr>)}<tr><th scope="row">Supplier notes</th>{p.offers.map(o=><td key={o.id}>{o.notes}</td>)}</tr><tr><th scope="row">Next action</th>{p.offers.map(o=><td key={o.id}><button className={`fab-button ${p.selectedOffer===o.id?'fab-dark':'fab-outline'}`} onClick={()=>select(o)}>{p.selectedOffer===o.id?'Selected in demo':'Select for discussion'}</button></td>)}</tr></tbody></table></div>
      <div className="fab-offer-mobile">{p.offers.map(o=><article className="fab-surface" key={o.id}><h3>{o.supplier}</h3><span className="fab-status">{!comparable(o,p.brief.quantity)?'Review differences':subtotal(o)===lowest?'Lowest subtotal':'Comparable offer'}</span><dl>{rows.map(([label,fn])=><div key={label} className={label==='Quoted subtotal'?'fab-total-row':''}><dt>{label}</dt><dd>{fn(o)}</dd></div>)}</dl><p>{o.notes}</p><button className="fab-button fab-dark" onClick={()=>select(o)}>{p.selectedOffer===o.id?'Selected in demo':'Select for discussion'}</button></article>)}</div>
      <div className="fab-notice"><Icon name="info" size={18}/><span>Lowest unit price may not mean lowest subtotal. Offers with a different quantity, proposed specification changes, or different exclusions are flagged and excluded from the comparable highlights.</span></div></>:<div className="fab-empty"><Icon name="file" size={30}/><h3>No quotes on this draft yet.</h3><p>Drafts do not generate live supplier responses.</p><button className="fab-button fab-dark" onClick={onSample}>Explore the example quote comparison</button></div>}</TabsContent>
      <TabsContent value="questions" className="fab-tab-panel"><div className="fab-surface"><h2>Keep the specification conversation together.</h2><p className="fab-muted">Demo conversation · Nothing is emailed or sent to a supplier.</p><div className="fab-conversation">{p.questions.length?p.questions.map(q=><article key={q.id}><strong>{q.author}</strong><p>{q.text}</p></article>):<p>No questions yet. Try asking about a tolerance or finish.</p>}</div><form className="fab-message-form" onSubmit={e=>{e.preventDefault();if(!message.trim())return;onChange({...p,questions:[...p.questions,{id:crypto.randomUUID(),author:'Buyer · demo',text:message.trim()}]});setMessage('');setNotice('Reply saved in this demo conversation. Nothing sent.');}}><label>Your reply<textarea required minLength={3} maxLength={2000} rows={3} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Clarify a requirement or ask a question…"/></label><button className="fab-button fab-dark" type="submit">Save demo reply</button></form></div></TabsContent>
      <TabsContent value="next" className="fab-tab-panel"><div className="fab-surface"><h2>Before a production order</h2><p className="fab-muted">A guide to the next conversation. The preview cannot place orders or process payments.</p><ol className="fab-next-steps">{['Resolve dimensions, tolerances, finish, and any quote exclusions.','Confirm the actual production location and the evidence behind supplier claims.','Agree on a sample or first article and how it will be approved.','Confirm the complete price, payment terms, inspection criteria, and delivery date.','Place a documented purchase order once the requirements are agreed.'].map((x,i)=><li key={x}><span>{String(i+1).padStart(2,'0')}</span><p>{x}</p></li>)}</ol>{selected&&<div className="fab-notice"><Icon name="check" size={18}/><span>{selected.supplier} is selected for discussion in this demo. No order has been placed.</span></div>}<button className="fab-button fab-outline" onClick={()=>setTab('questions')}>Return to project questions</button></div></TabsContent>
    </Tabs>{notice&&<div className="fab-inline-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notice"><Icon name="close" size={16}/></button></div>}
  </section>;
}
