"use client";
import { useState } from 'react';
import { Icon } from '@/components/ui/icons';
import { suppliers } from '@/lib/manufacturing/catalog';
import { money, parseCents, subtotal, type Offer, type Project } from '@/lib/manufacturing/sourcing';
import type { CapacityOverride } from './supplier-evidence';
export default function SupplierDesk({ project:p, onChange, onCapacity, onBuyer, onProfile }: {project:Project;onChange:(p:Project)=>void;onCapacity:(id:string,c:CapacityOverride)=>void;onBuyer:()=>void;onProfile:()=>void}) {
 const [supplierId,setSupplierId]=useState('precision');
 const [action,setAction]=useState<'quote'|'question'|'decline'>('quote');
 const [notice,setNotice]=useState('');
 const status=p.responses?.[supplierId]??'Open example opportunity';
 const s=suppliers.find(x=>x.id===supplierId)!;
 return <section className="fab-supplier-screen"><div className="fab-project-heading"><div><span className="fab-eyebrow">MANUFACTURER WORKSPACE · DEMO</span><h1>Good projects. Clear requirements.</h1><p>Review the brief, ask for detail, or prepare a quote.</p></div><button className="fab-button fab-outline" onClick={onProfile}>Create a factory profile</button></div><div className="fab-notice"><Icon name="info" size={18}/><span>Try the supplier side of this example. Responses and availability changes stay in this preview; no emails are sent.</span></div><div className="fab-project-columns"><div className="fab-surface"><div className="fab-panel-heading"><h2>{p.brief.title}</h2><span className="fab-status">{status}</span></div><p>{p.brief.quantity.toLocaleString()} units · {p.brief.material||'Material needs advice'} · {p.brief.destination}</p><p className="fab-muted">{p.brief.description}</p><button className="fab-text-action" onClick={onBuyer}>Read the complete project brief <Icon name="chevron-right" size={17}/></button><label className="fab-standalone-label">Respond as an example manufacturer<select value={supplierId} onChange={e=>{setSupplierId(e.target.value);setNotice('');}}>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="fab-action-switch" role="group" aria-label="Supplier response type">{(['quote','question','decline'] as const).map(a=><button key={a} aria-pressed={action===a} onClick={()=>setAction(a)}>{a==='quote'?'Prepare quote':a==='question'?'Ask a question':'Decline'}</button>)}</div>
 {action==='quote'?<form key={supplierId} className="fab-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);try {const offer:Offer={id:crypto.randomUUID(),supplier:`${s.name} · demo reply`,quantity:Number(f.get('quantity')),unitCents:parseCents(String(f.get('unit'))),toolingCents:parseCents(String(f.get('tooling'))),shippingCents:parseCents(String(f.get('shipping'))),inspectionCents:parseCents(String(f.get('inspection'))),leadDays:Number(f.get('lead')),validUntil:String(f.get('valid')),specification:String(f.get('specification')) as Offer['specification'],exclusions:String(f.get('exclusions')).trim(),notes:String(f.get('notes')).trim()};if(!Number.isInteger(offer.quantity)||offer.quantity<1||!Number.isInteger(offer.leadDays)||offer.leadDays<1)throw new Error('Enter a whole quantity and lead time.');if(offer.notes.length<5||!offer.exclusions.trim())throw new Error('Add quote assumptions and exclusions; blank spaces do not count.');onChange({...p,offers:[...p.offers,offer],responses:{...p.responses,[supplierId]:'Demo quote prepared'}});setNotice(`Demo quote saved: ${money(subtotal(offer))} subtotal. Open the buyer workspace to compare it.`);}catch(error){setNotice(error instanceof Error?error.message:'Check the quote amounts.');}}}>
 <label>Quoted quantity<input name="quantity" required type="number" min={1} max={10000000} step={1} defaultValue={p.brief.quantity}/></label><label>Unit price · USD<input name="unit" required type="number" min="0.01" max="1000000" step="0.01" placeholder="4.25"/></label>{[['tooling','Tooling / setup'],['shipping','Shipping'],['inspection','Inspection']].map(([name,label])=><label key={name}>{label} · USD<input name={name} required type="number" min="0" max="1000000" step="0.01" defaultValue="0"/></label>)}<label>Lead time after approval · days<input name="lead" required type="number" min={1} max={730} step={1} placeholder="28"/></label><label>Quote valid through<input name="valid" required type="date" min={new Date().toLocaleDateString('en-CA')}/></label><label>Specification alignment<select name="specification"><option>Matches brief</option><option>Changes proposed</option></select></label><label className="fab-full">Exclusions<input name="exclusions" required maxLength={200} defaultValue="Taxes excluded"/></label><label className="fab-full">Notes, assumptions, or proposed changes<textarea name="notes" required minLength={5} maxLength={2000} rows={3} placeholder="Confirm finish, inspection, tooling, and anything different from the brief."/></label><button className="fab-button fab-dark fab-full" type="submit">Save demo quote</button></form>:<form key={`${supplierId}-${action}`} className="fab-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const text=String(f.get('response')).trim();if(text.length<5){setNotice('Add at least five characters to the question or decline reason.');return;}onChange({...p,questions:[...p.questions,{id:crypto.randomUUID(),author:`${s.name} · ${action==='decline'?'declined in demo':'demo question'}`,text}],responses:{...p.responses,[supplierId]:action==='decline'?'Declined in demo':'Clarification requested in demo'}});setNotice(action==='decline'?'Decline saved with its reason. The project remains available.':'Question saved in the project conversation. Nothing sent.');e.currentTarget.reset();}}><label className="fab-full">{action==='decline'?'Reason for declining':'What do you need to know?'}<textarea required minLength={5} maxLength={2000} name="response" rows={4} placeholder={action==='decline'?'e.g. We cannot meet the required delivery window.':'e.g. Does the tolerance apply before or after finishing?'}/></label><button type="submit" className="fab-button fab-dark fab-full">{action==='decline'?'Save demo decline':'Save demo question'}</button></form>}
 </div><aside className="fab-surface"><span className="fab-eyebrow">YOUR PRODUCTION AVAILABILITY</span><h2>Help suitable buyers find you.</h2><form key={supplierId} className="fab-form fab-single-column" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!String(f.get('available')).trim()||!String(f.get('batch')).trim()){setNotice('Describe the next opening and preferred batch size.');return;}onCapacity(supplierId,{accepting:f.get('accepting')==='yes',available:String(f.get('available')),batch:String(f.get('batch')),expires:String(f.get('expires'))});setNotice(`Example availability saved for ${s.name}. Visible on its marketplace profile in this tab.`);}}><label>Accepting new work?<select name="accepting"><option value="yes">Yes, considering projects</option><option value="no">No, request confirmation</option></select></label><label>Next opening<input name="available" required maxLength={120} placeholder="Prototype slots in 2–3 weeks"/></label><label>Preferred batch size<input name="batch" required maxLength={100} placeholder="25–1,000 parts"/></label><label>Availability valid through<input name="expires" required type="date" min={new Date().toLocaleDateString('en-CA')}/></label><button className="fab-button fab-outline" type="submit">Save demo availability</button><p className="fab-muted">Expired availability requires confirmation. These are sample declarations, not a live factory schedule.</p></form><button className="fab-button fab-outline" onClick={onBuyer}>View buyer workspace</button></aside></div>{notice&&<div className="fab-inline-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss notice"><Icon name="close" size={16}/></button></div>}</section>;
}
