"use client";
import { useState } from 'react';
import { Icon } from '@/components/ui/icons';
import { suppliers } from '@/lib/manufacturing/catalog';
import { money, productUnitCents, type Brief, type Product } from '@/lib/manufacturing/sourcing';
export function ProductCard({ product:p, onOpen }: { product:Product; onOpen:()=>void }) {
 const s=suppliers.find(s=>s.id===p.supplierId)!;
 return <article className="fab-supplier-card fab-product-card"><button className="fab-product-image" onClick={onOpen} aria-label={`View ${p.name}`}><img src={`/manufacturing/${p.image}.png`} alt={`Illustrative ${p.name.toLowerCase()}`}/><span className="fab-example-tag">EXAMPLE PRODUCT</span></button><div className="fab-card-body"><span className="fab-eyebrow">{s.location}</span><h3>{p.name}</h3><p>{s.name}</p><div className="fab-product-price"><strong>{money(p.tiers[p.tiers.length-1]!.cents)}–{money(p.tiers[0]!.cents)}</strong><span>per {p.unit}</span></div><p className="fab-muted">Min. {p.minimum} {p.unit}s · {p.variants.length} variants</p><p className="fab-stock"><Icon name="box" size={16}/>{p.stock.toLocaleString()} {p.unit}s · example stock</p><div className="fab-card-footer"><button onClick={onOpen}>View product & pricing <Icon name="chevron-right" size={17}/></button></div></div></article>;
}
export function ProductDetail({ product:p, initial, onDraft }: { product:Product; initial?:Brief; onDraft:(b:Brief)=>void }) {
 const [quantity,setQuantity]=useState(initial?.catalog?.sample?p.minimum:initial?.quantity??p.minimum);
 const [variant,setVariant]=useState(initial?.catalog?.variant??p.variants[0]!);
 const [destination,setDestination]=useState(initial?.destination==='To be confirmed'?'':initial?.destination??'');
 const [error,setError]=useState('');
 const unit=productUnitCents(p,quantity);
 const valid=Number.isInteger(quantity)&&quantity>=p.minimum&&quantity<=p.stock;
 function draft(sample:boolean) {onDraft({id:crypto.randomUUID(),kind:'wholesale',catalog:{productId:p.id,variant,sample},title:`${sample?'Sample request':'Wholesale inquiry'}: ${p.name}`,quantity:sample?1:quantity,description:`${p.description}\nVariant: ${variant}. ${sample?`Sample catalog estimate: ${money(p.sampleCents)}.`:`Catalog estimate: ${money(unit)} per ${p.unit}, ${money(quantity*unit)} merchandise subtotal.`} Prices are illustrative. Shipping and taxes excluded.`,material:'Confirm product specification',dimensions:'Confirm product drawing / specification',finish:variant,destination:destination.trim()||'To be confirmed',target:'',requirements:sample?'Request a sample for review before any bulk order.':'Confirm stock, unit pricing, shipping, tax, and delivery before ordering.',process:'Catalog product',files:[],supplierIds:[p.supplierId]});}
 return <div className="fab-workspace fab-product-detail"><div className="fab-product-detail-top"><img src={`/manufacturing/${p.image}.png`} alt={`Illustrative ${p.name}`}/><div><span className="fab-eyebrow">WHOLESALE · EXAMPLE PRODUCT</span><h3>{p.name}</h3><p>{p.description}</p><p className="fab-stock">{p.stock.toLocaleString()} {p.unit}s available in this example</p></div></div><form className="fab-form" onSubmit={e=>{e.preventDefault();if(!destination.trim()){setError('Enter a delivery city, state, or ZIP. Blank spaces do not count.');return;}if(valid)draft(false);}}><label>Variant<select value={variant} onChange={e=>setVariant(e.target.value)}>{p.variants.map(v=><option key={v}>{v}</option>)}</select></label><label>Quantity ({p.unit}s)<input required type="number" step={1} min={p.minimum} max={p.stock} value={quantity||''} onChange={e=>setQuantity(Number(e.target.value))}/></label><div className="fab-price-tiers fab-full">{p.tiers.map((t,i)=>{const end=p.tiers[i+1]?.minimum;return <button type="button" key={t.minimum} aria-pressed={quantity>=t.minimum&&(!end||quantity<end)} onClick={()=>setQuantity(t.minimum)}><span>{t.minimum}{end?`–${end-1}`:'+'} {p.unit}s</span><strong>{money(t.cents)}</strong><small>per {p.unit}</small></button>;})}</div><label className="fab-full">Delivery destination<input required maxLength={150} value={destination} onChange={e=>setDestination(e.target.value)} placeholder="City, state or ZIP"/></label><div className="fab-full">{error&&<p className="fab-error" role="alert">{error}</p>}</div><div className="fab-catalog-total fab-full"><div><span>Example merchandise subtotal</span><strong>{valid?money(unit*quantity):'Enter a valid quantity'}</strong></div><p>Shipping and taxes excluded. Stock and prices require supplier confirmation.</p></div><div className="fab-form-actions fab-full"><button type="button" className="fab-button fab-outline" onClick={()=>draft(true)}>Request a sample · {money(p.sampleCents)}</button><button type="submit" disabled={!valid} className="fab-button fab-dark">Create inquiry draft</button></div><p className="fab-muted fab-full">Both actions create a local draft. Nothing is ordered, sent, or charged.</p></form></div>;
}
