"use client";
import { useState, type FormEvent } from "react";
import { Icon } from "@/components/ui/icons";
import type { Supplier } from "@/lib/manufacturing/catalog";

export type QuoteDraft = { project: string; quantity: string; process: string; material: string; target: string; specifications: string; reference: string; suppliers: string[] };
export const emptyQuote: QuoteDraft = { project: "", quantity: "", process: "I need help choosing", material: "", target: "", specifications: "", reference: "", suppliers: [] };
function downloadText(name: string, text: string) {
  const url = URL.createObjectURL(new Blob([text], { type: "text/plain;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = name;
  document.body.appendChild(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function QuoteWorkspace({ initial, onSave }: { initial: QuoteDraft; onSave: (draft: QuoteDraft) => void }) {
  const [draft, setDraft] = useState(initial);
  const [review, setReview] = useState(false);
  const [downloaded, setDownloaded] = useState(false);
  const field = (name: keyof QuoteDraft, value: string) => { const next = { ...draft, [name]: value }; setDraft(next); onSave(next); };
  const today = new Date();
  const todayLocal = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`;
  return <div className="fab-workspace">
    <div className="fab-form-progress"><span className={!review ? "active" : ""}>01 &nbsp; Project details</span><span>→</span><span className={review ? "active" : ""}>02 &nbsp; Review your request</span></div>
    <div className="fab-notice"><Icon name="info" size={17} /><span>This preview prepares a downloadable draft. No request is sent to a manufacturer.</span></div>
    {review ? <div className="fab-review"><h3>{draft.project}</h3><dl><div><dt>Quantity</dt><dd>{draft.quantity} units</dd></div><div><dt>Manufacturing process</dt><dd>{draft.process}</dd></div><div><dt>Material</dt><dd>{draft.material || "Open to recommendations"}</dd></div><div><dt>Target delivery</dt><dd>{draft.target || "Flexible"}</dd></div><div><dt>Example suppliers</dt><dd>{draft.suppliers.join(", ") || "Supplier to be selected"}</dd></div><div><dt>Specifications</dt><dd className="fab-preserve">{draft.specifications}</dd></div>{draft.reference && <div><dt>Drawing / specification link</dt><dd>{draft.reference}</dd></div>}</dl><p className="fab-muted">Pricing, tooling, shipping, inspection requirements, and final delivery dates must be agreed with a real supplier.</p><div className="fab-form-actions"><button className="fab-button fab-outline" onClick={() => { setReview(false); setDownloaded(false); }}>Edit details</button><button className="fab-button fab-dark" onClick={() => { downloadText("fab-rent-rfq-draft.txt", `FAB.RENT — REQUEST FOR QUOTE DRAFT\nDesign preview. Not sent. Example suppliers are fictional.\n\nProject: ${draft.project}\nQuantity: ${draft.quantity} units\nProcess: ${draft.process}\nMaterial: ${draft.material || "Open to recommendations"}\nTarget delivery: ${draft.target || "Flexible"}\nExample suppliers: ${draft.suppliers.join(", ") || "To be selected"}\n\nSpecifications:\n${draft.specifications}\n\nDrawing/specification link: ${draft.reference || "None supplied"}\n\nPlease quote unit pricing, tooling/setup costs, lead time, shipping, inspection, and payment terms separately.\n`); setDownloaded(true); }}><Icon name="download" size={16} />Download RFQ draft</button></div>{downloaded && <p role="status" className="fab-success">Your draft download is ready. Nothing has been sent.</p>}</div> : <form className="fab-form" onSubmit={(e: FormEvent) => { e.preventDefault(); onSave(draft); setReview(true); }}>
      <label className="fab-full">What do you need made?<input required maxLength={140} value={draft.project} onChange={e => field("project", e.target.value)} placeholder="e.g. Custom aluminum enclosure for a sensor" /></label>
      <label>Quantity<input required type="number" min="1" max="10000000" step="1" value={draft.quantity} onChange={e => field("quantity", e.target.value)} placeholder="250" /></label>
      <label>Process<select value={draft.process} onChange={e => field("process", e.target.value)}>{["I need help choosing", "CNC machining", "Metal fabrication", "Electronics", "Textiles & apparel", "Plastics & molding", "Packaging"].map(p => <option key={p}>{p}</option>)}</select></label>
      <label>Material <span>optional</span><input maxLength={160} value={draft.material} onChange={e => field("material", e.target.value)} placeholder="e.g. 6061 aluminum, or help me choose" /></label>
      <label>Target delivery <span>optional</span><input type="date" min={todayLocal} value={draft.target} onChange={e => field("target", e.target.value)} /></label>
      <label className="fab-full">Project specifications<textarea required minLength={15} maxLength={6000} rows={4} value={draft.specifications} onChange={e => field("specifications", e.target.value)} placeholder="Dimensions, finish, tolerances, use case, and any testing or certification requirements…" /></label>
      <label className="fab-full">Drawing or specification link <span>optional</span><input type="url" maxLength={2000} value={draft.reference} onChange={e => field("reference", e.target.value)} placeholder="https://…" /><small>Reference only. The preview does not fetch or upload your documents.</small></label>
      <div className="fab-full fab-recipient"><Icon name="users" size={16} /><span>{draft.suppliers.length ? `Prepared for: ${draft.suppliers.join(", ")}` : "Select a supplier later, or start from your shortlist."}</span></div>
      <div className="fab-full fab-form-actions"><span className="fab-muted">Draft stays in this tab until you download it.</span><button className="fab-button fab-dark" type="submit">Review request <span>↗</span></button></div>
    </form>}
  </div>;
}
export function SupplierProfile({ supplier: s, onQuote, onSave, saved }: { supplier: Supplier; onQuote: () => void; onSave: () => void; saved: boolean }) {
  return <div className="fab-workspace"><div className="fab-profile-header"><span className="fab-profile-monogram">{s.initials}</span><div><span className="fab-eyebrow">EXAMPLE MANUFACTURER</span><p><Icon name="pin" size={15} />{s.location} · {s.region}</p></div></div><h3 className="fab-profile-title">{s.title}</h3><p className="fab-muted">{s.description}</p><div className="fab-profile-columns"><section><h4>Manufacturing capabilities</h4>{s.capabilities.map(c => <p key={c}><Icon name="check" size={15} />{c}</p>)}</section><section><h4>Project fit</h4><dl><div><dt>Materials</dt><dd>{s.materials.join(", ")}</dd></div><div><dt>Production scale</dt><dd>{s.scale}</dd></div><div><dt>Minimum order</dt><dd>{s.minOrder} units</dd></div><div><dt>Typical lead time</dt><dd>{s.lead}</dd></div></dl></section></div><div className="fab-notice"><Icon name="info" size={17} /><span>Fictional company and illustrative specifications. No business location, certifications, capacity, or lead times have been verified. Catalog images are AI-generated illustrations of manufacturing.</span></div><div className="fab-form-actions"><button className="fab-button fab-outline" onClick={onSave}><Icon name={saved ? "heart-filled" : "heart"} size={16} />{saved ? "Saved to shortlist" : "Save to shortlist"}</button><button className="fab-button fab-dark" onClick={onQuote}>Prepare a quote request ↗</button></div></div>;
}
export function ManufacturerOnboarding() {
  const [complete, setComplete] = useState(false);
  return <div className="fab-workspace"><div className="fab-notice"><Icon name="info" size={17} /><span>Prepare an example supplier profile. Downloading a draft does not publish a listing or create an account.</span></div><form className="fab-form" onSubmit={e => { e.preventDefault(); const fields = new FormData(e.currentTarget); downloadText("fab-rent-manufacturer-profile.txt", `FAB.RENT — MANUFACTURER PROFILE DRAFT\nNot submitted or published.\n\n${Array.from(fields.entries()).map(([k,v]) => `${k}: ${v}`).join("\n\n")}\n\nBefore publication: confirm actual production address, business identity, processes, capacity, and documentary evidence for any certification.\n`); setComplete(true); }}><label className="fab-full">Company name<input name="Company" required maxLength={140} placeholder="Your manufacturing business" /></label><label>Production city<input name="Production city" required maxLength={100} placeholder="Where you make products" /></label><label>U.S. state<select required name="State" defaultValue=""><option value="" disabled>Select a state</option>{["Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming","District of Columbia"].map(s => <option key={s}>{s}</option>)}</select></label><label className="fab-full">What can your factory make?<textarea name="Capabilities" required minLength={15} maxLength={6000} rows={4} placeholder="Processes, materials, typical order sizes, equipment, and production capacity…" /></label><label className="fab-full">Company website <span>optional</span><input name="Website" type="url" placeholder="https://…" /></label><div className="fab-form-actions fab-full"><span className="fab-muted">Your information stays in this browser tab.</span><button className="fab-button fab-dark" type="submit"><Icon name="download" size={16} />Download profile draft</button></div>{complete && <p role="status" className="fab-success fab-full">Your profile draft download is ready. Nothing is published.</p>}</form></div>;
}
