/**
 * Generates supabase/seed.sql — the Port Maren demo — anchored to DEMO_NOW (default Sat 5 Sep 2026 10:00 market time).
 *   pnpm seed:generate
 */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { Sql, ANCHOR_ISO } from "./lib";
import { emitPeople } from "./people";
import { emitCatalog } from "./catalog";
import { emitBookings, emitAfterBookings } from "./bookings";
import { addReviewQueueListings, emitAdmin, emitConfig } from "./admin";

const sql = new Sql();
sql.rawSql(`-- fab.rent demo seed · generated by supabase/seed/generate.ts · anchor ${ANCHOR_ISO} (market time)\n-- Do not edit by hand: change the generator and re-run pnpm seed:generate.\nbegin;\nset local search_path = public, auth, storage, extensions;\n`);
addReviewQueueListings();
emitPeople(sql);
emitConfig(sql); // policies + settings first (listings reference cancellation_policies)
emitCatalog(sql);
const bookings = emitBookings(sql);
emitAfterBookings(sql, bookings);
emitAdmin(sql);
sql.rawSql("commit;");

const out = path.resolve("supabase/seed.sql");
writeFileSync(out, sql.toString());
console.log(`wrote ${out} (${(sql.toString().length / 1024).toFixed(0)} KB)`);
